declare module 'react-reveal/Fade'
declare module 'react-reveal/Zoom'
declare module 'react-reveal/Flip'
declare module 'react-reveal/Bounce'
declare module 'react-reveal/LightSpeed'
declare module 'react-reveal/RubberBand'
